

﻿#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: 1.4.2 RELEASE

settings:
  # セーフモードは、スコアボードがサーバーと同期されているか（true）、非同期されているか（false）を判別します。
  # 同期（セーフモード：true）は、より安定しています
  # 非同期（セーフモード：false）の方が高速ですが、場合によっては問題が発生する可能性があります
  safe-mode: false
  # サーバーのバージョンが1.13以降の場合は、longlineを有効にします。
  # true: 1行あたり128文字を使用できます（1.13以上）
  # false: 1行あたり32文字を使用できます（1.12以下
  longline: false

# スコアボードを無効にするワールド
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    interval: 3
    liner:
      - '&f&l> ZSHARE <'
  rows:
    1:
      interval: 5
      liner:
      - '---------------'
    2:
      interval: 80
      liner:
      - '&c名前:'
    3:
      interval: 80
      liner:
      - ' %player_name%'
    4:
      interval: 80
      liner:
      - ''
    5:
      interval: 80
      liner:
      - ' X:%player_x% Y:%player_y% Z:%player_z%'
    6:
      interval: 5
      liner:
      - ''
    7:
      interval: 80
      liner:
      - ''
    '8':
      interval: 80
      liner:
      - '所持金'
    '9':
      interval: 20
      liner:
      - ' %vault_eco_balance%円'
    10:
      interval: 80
      liner:
      - ''
    11:
      interval: 80
      liner:
      - 'おしらせ'
    12:
      interval: 80
      liner:
      - 'dash.zpw.jp'
    50:
      interval: 5
      liner:
      - '---------------'
